### ISSUE TITLE
error

### ISSUE THREAD

**Issue by genso413** [rgalyeon/Linea_Park#1]
Hey! got this error how to fix it?
 Start nidum mint
2024-03-20 13:56:30.137 | ERROR    | utils.helpers:wrapper:15 - Error | 'signature'
Traceback (most recent call last):
  File "C:\auto\Linea_Park-master\utils\helpers.py", line 12, in wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\auto\Linea_Park-master\utils\gas_checker.py", line 73, in _wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\auto\Linea_Park-master\modules\quests_week1.py", line 53, in nidum_mint
    signature = claim_data['signature']
                ~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'signature'

**Comment by rgalyeon** [comment]
Hey! There is an error somewhere when sending a request in the get_claim_data function in the nidim_sign.py file. I will try to fix it. Thank you!

**Comment by rgalyeon** [comment]
I fixed it. There was an error with the coroutine. If a KeyError occurs, you should wait for some time until the signature time expires and start the module again.
